[workspace]
resolver = "3"
members = [
    # ray-tracer library
    "crates/ray-tracer",

    # scene loading libraries
    "crates/scene-types",
    "crates/scene-loader",

    # Bevy integration for ray-tracer library output
    "crates/bevy-app", "crates/scene-types", "crates/scene-loader",
]
