[package]
name = "scene-loader"
version = "0.1.0"
edition = "2024"

[dependencies]
ray-tracer = { path = "../ray-tracer" }
scene-types = { path = "../scene-types" }
toml = "0.9.10"
thiserror = { workspace = true }
