[camera]
position = [0, 0, 0]
target = [0, 0, -1]
fov = 40.0

[ambient]
intensity = 0.4
color = [255, 255, 255]

[[lights]]
type = "point"
position = [-10, 10, -10]
intensity = 0.5
color = [255, 255, 255]

[[objects]]
type = "sphere"
position = [0, 0, -30]
radius = 5.0
material = {
        type = "custom",
        ambient-coefficient = 0.1,
        diffuse-coefficient = 0.9,
        specular-coefficient = 0.9,
        shininess = 200.0
    }
color = [136, 8, 8]

[[objects]]
type = "sphere"
position = [0, 0, -30]
radius = 5.0
material = { type = "default" }
color = [136, 8, 8]
